# These are all the cops that are disabled in the default configuration.

Style/Copyright:
  Enabled: false
Rails:
  Enabled: false
AllCops:
  Exclude:
    - 'lib/event_store_client/adapters/grpc/generated/*.rb'
